// ============================================================
// TermsPage — full terms of use (publicly accessible at /#/terms)
// Linked from the Supabase welcome email.
// ============================================================

import { Link } from 'react-router-dom'

export function TermsPage() {
  return (
    <div className="min-h-screen bg-abh-ltgrey" style={{ fontFamily: 'Arial, sans-serif' }}>
      {/* Header */}
      <div className="bg-abh-navy text-white px-4 py-4 flex items-center justify-between">
        <div>
          <h1 className="font-bold text-sm">Terms of Use</h1>
          <p className="text-blue-200 text-xs">Hero Shelf Check — Australian Beverage Holdings Pty Ltd</p>
        </div>
        <Link to="/login" className="text-blue-200 text-xs hover:text-white">
          Sign in
        </Link>
      </div>

      {/* Content */}
      <div className="max-w-2xl mx-auto px-4 py-6 space-y-5 text-sm text-gray-700">

        <p className="text-xs text-gray-400">Effective date: 18 August 2026</p>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">1. Authorised Use Only</h2>
          <p>This application (Hero Shelf Check) is provided exclusively for authorised field representatives of Australian Beverage Holdings Pty Ltd (ABH). Access is granted on a personal, non-transferable basis. You must not share your login credentials with any other person. Unauthorised use or access by a third party must be reported to ABH immediately.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">2. Accurate Data Recording</h2>
          <p>You are required to record shelf unit counts, backroom observations, and any other data fields accurately and honestly, reflecting what you personally observe at each store visit. Falsifying, estimating without counting, or otherwise recording inaccurate data is a serious breach of these Terms and grounds for immediate access termination and may result in further action.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">3. Photography</h2>
          <p>The photo capture feature must be used only to document Pureau product placement on retail shelving. You must not photograph customers, staff, children, personal identifying information, competitor pricing, or any area of a store not related to Pureau product placement. All photos captured become the property of Australian Beverage Holdings Pty Ltd and are stored securely on its servers.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">4. Confidentiality</h2>
          <p>All data, store-level information, sales figures, reports, and any other information accessible through or generated by this application are strictly confidential to Australian Beverage Holdings Pty Ltd. You must not disclose, distribute, copy, or use such information for any purpose other than your authorised field representative duties. These obligations survive termination of your access.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">5. Device Responsibility and Offline Sync</h2>
          <p>You are responsible for maintaining your device in a condition that allows the application to function. Visit data is stored on your device when offline and syncs automatically when a network connection is available. You must allow sync to complete before concluding any visit period. ABH accepts no liability for data lost due to device failure, uninstallation, or failure to allow sync to complete.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">6. Data Collection and Privacy</h2>
          <p>This application collects and stores the following data in connection with your account and visits:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Your name and email address</li>
            <li>Store visit records (store, date, time)</li>
            <li>Shelf unit counts per SKU</li>
            <li>Backroom availability observations</li>
            <li>Notes you enter</li>
            <li>Photos you capture</li>
            <li>Your acceptance of these Terms (timestamp)</li>
            <li>Device geolocation (future capability, Stage 3 only)</li>
          </ul>
          <p className="mt-2">This data is used solely for internal retail merchandising, compliance monitoring, and field operations reporting by Australian Beverage Holdings Pty Ltd. It is not sold or disclosed to third parties except as required by law.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">7. Intellectual Property</h2>
          <p>The Hero Shelf Check application, including all code, design, data structures, and content, is the intellectual property of Australian Beverage Holdings Pty Ltd. You have no right to copy, reverse engineer, modify, or redistribute any part of this application.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">8. Termination of Access</h2>
          <p>Australian Beverage Holdings Pty Ltd reserves the right to suspend or revoke your access to this application at any time, for any reason, without notice. Upon termination, your obligation of confidentiality and all other obligations that by their nature should survive, will continue to apply.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">9. Limitation of Liability</h2>
          <p>The application is provided on an "as is" basis. Australian Beverage Holdings Pty Ltd makes no warranty as to its availability, accuracy, or fitness for any particular purpose. To the maximum extent permitted by Australian law, ABH excludes all liability for loss or damage arising from your use of or inability to use this application.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">10. Governing Law</h2>
          <p>These Terms are governed by the laws of Queensland, Australia. Any disputes arising under these Terms are subject to the exclusive jurisdiction of the courts of Queensland.</p>
        </section>

        <section>
          <h2 className="font-bold text-abh-navy mb-2">Contact</h2>
          <p>Questions about these Terms may be directed to <a href="mailto:enquiries@abhgroup.com.au" className="text-abh-blue underline">enquiries@abhgroup.com.au</a></p>
        </section>

        <p className="text-xs text-gray-400 pt-4 border-t border-gray-200">
          Australian Beverage Holdings Pty Ltd — ABH Pureau Hero Shelf Check — All rights reserved
        </p>
      </div>
    </div>
  )
}
